mp-compras:
  compra-v2: /deprecated/api/compra/v2
  get-listinig: /deprecated/api/compra/listing
  auditoria-mensageria: /auditoriamensageria
  compra: /compra
  compra-atacado: /compra/atacado
  compra-servico: /compra/servico
  compra-invalida: /compra/invalida
  compra-pap: /compra/status/pagamento-aprovado
  compra-id: /compra/
  compra-bandeira: /compra/bandeira/
  get-callback: /callback
  post-callback: /callback
  log-integracao-lojista: /logintegracaolojista
  get-notificacao-lojista: /notificacaolojista
  post-store-notification: /notificacaolojista
  top-sku-by-seller: /ranking/topSkusByLojista
  pedidos-por-dia: /compra
  ticket-medio: /compra
  apagar-notificacao-lojista: /notificacaolojista
  compra-v1: /deprecated/api/compra
  cancelamento: /compra/cancelamento
  tracking: /deprecated/api/compra/orderTrackings
  ranking: /ranking
  aprovacao-pedido: /compra/aprovacao/pagamento
  master-id: /deprecated/api/compra/groupby/masterid
  cancelamento-antigo: /deprecated/api/compra/cancellment
  tracking-entregue: /compra/tracking/entregue
  auditoria-integracao-front: /auditoriaintegracaofront
  cancelamento-item-antigo: /deprecated/api/compra/cancellment/item
  status-ar1: /compra/status/ar1
  status-ar2: /compra/status/ar2
  notificacao-reenvia-front-entrega: /notificacao/reenvia/front/entrega
  notificacao-reenvia-front-entrega-id: /notificacao/reenvia/front/entrega/id
  notificacao-reenvia-tracking-entrega: /notificacao/reenvia/tracking/entrega
  notificacao-reenvia-tracking-entrega-id: /notificacao/reenvia/tracking/entrega/id
  cancelamento-entrega: /compra/cancelamento-entregas